
# Input sequence
s = "GAGTGGGCAGACAGGTATCCCAGTAGTAGCAATATACACCGCAGCTATGAGTGTTCCTATATGACGCGGAAGACGTACGCGTCTTCCTGGTCCAGAGATTGAAGAGCAGTGAAGGTAGGGGATTTTTTTGAGAGTTTCCGGTCTCGAACCTTCCGAATCGCATAGCACGCATAGCCACTATTACAAAACGCACATAACGCGATTATATTTATGTAGAGTGAGATTCTGCAAATTGCCTAGTTCAACTTTCAGGGTTTTACTAGCTAATCTCAGGTAACCGGTTCTAACGGATGTGCACTATCCGGCTGTGACTATCAGAGACTCAGATACAGGTGTAGGTCGGATGAGACGAAATCTAAGCAGGTGTTAGGTGTGTGCGTCAAGGACTGAAAGTGTATAGAACCGATCACATATTTGCTCAAGCTTAAAGGGTATTCTTTAAACTGATCACTAAAAGCAAGGAAAATAGTGGAGCGTGGACCCGACAGCGTGGTAAGTGCTGGACGGCTCTTGCTCTAAATTTTCCGGCGTGAGCCAATCAGCTTTCCCTGATACCGTCGGACAGTCACGTGTCTGACGCATCGGAACCCTGTTAAGCGTTGGCCGGAGGCCCTTGTGTGCGGACGCTGTGCCATGCTGCGCCTCCCTTATTCTCGGTATAAGTCCATGCCCATGAAATTGTCCTAGCTGAACCGCGAATTCTGGTGAGTGAGGGGTAAGGCTCGCGCCAATTCGTGACTAAAACAGCCCCCCCCGTAGAACCTCTGGACTGGCTGGCCTCACAGTTCTAGTACCGTAAAATCTAGTGATGTAAATAT"
sclist = []

# Dictionary with the bases and their complements
compdic = {
    "A": "T",
    "C": "G",
    "G": "C",
    "T": "A"
}

# Create a reversed list with the characters of the input sequence
slist = list(s)
srevlist = reversed(slist)

# Add the complement of each base to the output list
for i in srevlist:
    compb = compdic[i]
    sclist.append(compb)

#Make a string and print it
sc = "".join(sclist)
print(sc)