
# Input sequence and an empty list to put the RNA sequence in
t = "GAACCATCGACCGGCAGTTTGCCTTATCAGATTTAAGGCACGGGCTTCAGCTCTCTCTCGCACAATTACCCGTCCCTGCCGATATCGTTGTCTTTGATGAGTTTGATTGGGAAAGGCTCGTAAAGATGTTATGGAACGCCCCACATTTCGGTAGTATGCGATCTTCAGCAGAAGTGCGAGTATCAAACCGCAAAGGTGTCAGTATACATCTGAGCCGAAAGAACGCAAGCTTTACGACTACATTACGGCGGAACTGGGCTAGTCAGAGCAAGGATTACAAGGCCCCCAAGCTCTATGATTTTCATGATGAGGCGGTATCCAAGGACGGACGGGCTATACTCCGCGAACGATTTATTATTTTGACGGTTCCTCAGGGTCCCGAAAGGTTATGTGTTAAGTAGGTTTTGCTAGCTCCACCCTATCTCGTAGTCTACGGGTGTTAAACCACTCTCTATGTCTTGACGCGAATTATCACGAGAGGAATGTGCACCCGGAAGCTCAGTAAATGTCTTCCATAATACGTGTTACTCCTAATAGCAGCGAGGATGCACCTGATGTTATGGTGAAATGGCCGCTGCAATTGACTCCCGTCGGGCGTGTGCGCATTACCTTTAAGCATGTTGTCCAACACACACAGAAGTATCGGATAGGTGGGCCGTTCAGGGGATGTGTCGACCCATCTAAGTAACGGTATCTATAGAGCCTCCGTGAATTATAGCAGCTACAGTCTACTCCCCCACGGGTCCAGTAGAGATCGAAAACCGTCGGCTTGGACTCGTCCATAGAACAAGACACACAAGGGACCAGCGACGACTTCTTTGGCATCTTAGCATTGTTGTAGATGAAGATCATCCTGTTCGAGTCAATCGATGATAGTTATAATATTATAGGTCTTCGGGTGGAAAAGTAGTTGCAGGGGATGCATAATCTTAGCTCAGACGACTAAACTGCTCCTATAAGCGCACTGTCA"
ulist = []

# At each position in the sequence, check if it's a T, in that
# case put a U in the RNA list. If not, just put the base.
for i in range(len(t)):
    if t[i] == "T":
        ulist.append("U")
    
    else:
        ulist.append(t[i])

# Create a string from the list we made and print it
u = "".join(ulist)
print(u)